spring.profiles.active=true
spring.application.name=leaveManagement


# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/leave_management
#spring.datasource.username=postgres
#spring.datasource.password=Tejas@1410
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://ep-silent-union-ad77co1h-pooler.c-2.us-east-1.aws.neon.tech:5432/leave_management?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_isHBo8yjL9eC
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.outOfOrder=true

#mybatis.mapper-dao-locations=com.pheonix.leavemanagement.daos
mybatis.mapper-locations=classpath*:com/pheonix/leaveManagement/daos/impls/*.xml